### ISSUE TITLE
Typesetting using LaTeX

### ISSUE THREAD

**Issue by aomader** [jbmouret/matplotlib_for_papers#1]
I'm using [gnuplot](http://gnuplot.sourceforge.net/) in combination with [gnuplottex](http://www.ctan.org/pkg/gnuplottex) to create all my graphs. It allows for an incredible easy and efficient workflow and allows me to typeset the text in my graphs using LaTeX. `gnuplottex` automates the process of generating a `*.pdf` containing the actual drawings in combination with a `*.tex` file including the drawing and overlaying the text at the appropriate positions using LaTeX.
1. Is it possible to generate `*.tex`/`*.pdf` combinations in a similar way, such that I can use LaTeX and all my document specific settings to typeset my text?
2. If so, is there something analog to `gnuplottex` in order to simplify the workflow?

For example, to generate the following output
![graph using gnuplottex](https://paste.xinu.at/MfP/)
I use the code below, ran with `pdflatex` just once.

``` tex
\documentclass{article}

\usepackage[miktex]{gnuplottex}
\usepackage[pdftex]{color}

\begin{document}
    \begin{figure}[htbp]
        \footnotesize\centering
        \begin{gnuplot}[terminal=cairolatex, terminaloptions={color colortext pdf size 3,2}]
            load 'common.plt'

            set xtics 0, 1
            set ytics -1, 1
            set xrange [0:2*pi]
            set xlabel '$x$'
            set ylabel '$\sin(x)$'

            plot sin(x) title '$\sin(x)$'
        \end{gnuplot}
        \caption{$\sin(x)$}
    \end{figure}
\end{document}
```

**Comment by jbmouret** [comment]
Hi

First, note that you can use LaTeX for text rendering in matplotlib. You can even add a preamble:
rc('text', usetex=True)
matplotlib.rcParams['text.latex.preamble'] = ['\usepackage{siunitx}']

I suppose you can put all your document-specific settings in a package and rely on \usepackage{your_settings} to use them.

Something closer to your example is to use the pgf backend, which generates pgf commands that can be executed by latex.
See: http://matplotlib.org/users/pgf.html
''Using the pgf backend, matplotlib can export figures as pgf drawing commands that can be processed with pdflatex, xelatex or lualatex. XeLaTeX and LuaLaTeX have full unicode support and can use any font that is installed in the operating system, making use of advanced typographic features of OpenType, AAT and Graphite. Pgf pictures created by plt.savefig('figure.pgf') can be embedded as raw commands in LaTeX documents"

It also seems (I never tried) that you can embed python code into latex:
http://tex.stackexchange.com/questions/121877/embedding-python-in-latex-hello-example

Putting everything together: I believe it's possible to do something similar to what you do with gnuplot, but I never tried. If you manage to do it, don't hesitate to do a pull request and I will include your contribution in the tutorial.
