### ISSUE TITLE
Directory Structure mismatch

### ISSUE THREAD

**Issue by JTekGT** [jbmouret/matplotlib_for_papers#8]
I have been following the tutorial for the plotting and had issues with the glob function finding the bestfit.dat files.  I used the files from data.tar.gz.  The folder structure of the code does not match the folder structure of the compressed file.  There is no data folder and the high_mut folder extracts as matplotlib_high_mut.  These differences made it to where none of the data or plots were generated.  I was able to correct the folder names and continue with the tutorial, but I feel that others may not have.  Thank you- JT

**Comment by jbmouret** [comment]
Thanks. I will have a look soon.

**Comment by jbmouret** [comment]
This should be fixed.
